// go.mkdef -w -pub=false console_unix.go sys_unix.go def_bsd.go
// MACHINE GENERATED BY go.mkdef (github.com/kless/cutil); DO NOT EDIT
//
// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs _zdef_darwin_amd64.go

package console

const (
	_BRKINT     = 0x2
	_CS8        = 0x300
	_CSIZE      = 0x300
	_ECHO       = 0x8
	_ECHONL     = 0x10
	_ICANON     = 0x100
	_ICRNL      = 0x100
	_IEXTEN     = 0x400
	_IGNBRK     = 0x1
	_IGNCR      = 0x80
	_INLCR      = 0x40
	_ISIG       = 0x80
	_ISTRIP     = 0x20
	_IXON       = 0x200
	_OPOST      = 0x1
	_PARENB     = 0x1000
	_PARMRK     = 0x8
	_TCSADRAIN  = 0x1
	_TCSAFLUSH  = 0x2
	_TCSANOW    = 0x0
	_TCGETS     = 0x40487413
	_TIOCGWINSZ = 0x40087468
	_TCSETS     = 0x80487414
	_TCSETSF    = 0x80487416
	_TCSETSW    = 0x80487415
	_VMIN       = 0x10
	_VTIME      = 0x11
)

type termios struct {
	Iflag     uint64
	Oflag     uint64
	Cflag     uint64
	Lflag     uint64
	Cc        [20]uint8
	Pad_cgo_0 [4]byte
	Ispeed    uint64
	Ospeed    uint64
}
type winsize struct {
	Row    uint16
	Col    uint16
	Xpixel uint16
	Ypixel uint16
}
