// go.mkdef -w -pub=false terminal_unix.go sys_unix.go def_linux.go
// MACHINE GENERATED BY go.mkdef (github.com/kless/cutil); DO NOT EDIT
//
// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs _zdef_linux_amd64.go

package terminal

const (
	_BRKINT     = 0x2
	_CS8        = 0x30
	_CSIZE      = 0x30
	_ECHO       = 0x8
	_ECHOE      = 0x10
	_ECHOK      = 0x20
	_ECHONL     = 0x40
	_ICANON     = 0x2
	_ICRNL      = 0x100
	_IEXTEN     = 0x8000
	_IGNBRK     = 0x1
	_IGNCR      = 0x80
	_INLCR      = 0x40
	_ISIG       = 0x1
	_ISTRIP     = 0x20
	_IXON       = 0x400
	_OPOST      = 0x1
	_PARENB     = 0x100
	_PARMRK     = 0x8
	_TCGETS     = 0x5401
	_TCSADRAIN  = 0x1
	_TCSAFLUSH  = 0x2
	_TCSANOW    = 0x0
	_TCSETS     = 0x5402
	_TCSETSF    = 0x5404
	_TCSETSW    = 0x5403
	_TIOCGWINSZ = 0x5413
	_VMIN       = 0x6
	_VTIME      = 0x5
)

type termios struct {
	Iflag uint32
	Oflag uint32
	Cflag uint32
	Lflag uint32
	Line  uint8
	Cc    [19]uint8
}
type winsize struct {
	Row    uint16
	Col    uint16
	Xpixel uint16
	Ypixel uint16
}
